language: go
go:
- 1.10.2

install:
- mkdir -p /home/travis/gopath/bin
- mkdir -p /home/travis/gopath/pkg
- cd $HOME/gopath/src/github.com
- mv `ls` foo
- mv foo minishift
- cd minishift/minishift
- GODEP_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
- GODEP_TAG=v0.4.1
- GODEP_LATEST_RELEASE_URL="https://github.com/golang/dep/releases/download/${GODEP_TAG}/dep-${GODEP_OS_ARCH}"
- mkdir /tmp/godep
- wget ${GODEP_LATEST_RELEASE_URL} -O /tmp/godep/dep
- chmod +x /tmp/godep/dep
- export PATH=$PATH:/tmp/godep/

script:
- make prerelease

notifications:
  webhooks: http://minibot.19cf262c.svc.dockerapp.io:9009/hubot/travis-ci
